enableScripts: true

# httpProxy: ${BERRY_RC_HTTP_PROXY-http://127.0.0.1:51457}

# httpsProxy: ${BERRY_RC_HTTPS_PROXY-http://127.0.0.1:51457}

# It's OK if you see red underline here.
npmRegistryServer: ${BERRY_RC_NPM_REGISTRY-https://registry.npm.taobao.org}

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-2.4.0.cjs
