version: "3.6"
services:
  web:
    image: nginx
    container_name: nginx_feedx_dev
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/www/:/www
    ports:
      - 3001:3001
  pg:
    image: postgres:13
    container_name: pg_feedx_dev
    restart: always
    volumes:
      - feedx_data:/var/lib/postgresql/data
      - ./pg/seeds:/seeds
      - ./pg/initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_ROOT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
  pga:
    image: dpage/pgadmin4
    container_name: pga_feedx_dev
    restart: always
    depends_on:
      - pg
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
volumes:
  feedx_data: ~
